### ISSUE TITLE
Deploy Resulting Docker Image to Server for milestone:"users and permissions" 

### ISSUE THREAD

**Issue by njordan-hsr** [geometalab/osmaxx#125]
- [x] document deployment process
- [x] deploy to staging environment
- [ ] add link to deployed website on http://giswiki.hsr.ch/Osmaxx

**Comment by wasabideveloper** [comment]
Deployed and updated deployment documentation.
